title: Duplicate costumes in Scratch
hero_image: images/banner.png
description: How to duplicate costumes in Scratch
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests: ""
technologies: "scratch"
steps:
  - title: Duplicating costumes
